'use strict';
const $=s=>document.querySelector(s),app=$('#app'),KEY='toki-history-learned-v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function parseCSV(text){let rows=[],row=[],cell='',q=false;for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){cell+='"';i++;}else q=!q;}else if(c===','&&!q){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=c;}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows;}
function yearInfo(y){const n=Number((y.match(/\d+/)||[])[0]);return{n,bc:/B\.?C|紀元前/i.test(y),century:y.includes('世紀')};}
function time(y){const t=yearInfo(y);return t.bc?-t.n:t.century?(t.n-1)*100+1:t.n;}
function compare(a,b){return time(a.year)-time(b.year)||Number(a.no)-Number(b.no)||a.row-b.row;}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
let data=[],learned=new Set(),sound=true,mode='',selected=new Set(),exclude=true,pool=[],queue=[],qIndex=0,correct=0,current=null,answered=false,choice=null,order=[],orderItems=[],digits='',speaking=null,audioCtx=null;
try{learned=new Set(JSON.parse(localStorage.getItem(KEY)||'[]'));sound=localStorage.getItem('toki-sound')!=='off';}catch{}
function toast(t){$('#notice').textContent=t;$('#notice').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#notice').style.display='none',4000);}
function setLearned(id,v){v?learned.add(id):learned.delete(id);try{localStorage.setItem(KEY,JSON.stringify([...learned]));}catch{toast('記録を保存できません。ブラウザの保存設定をご確認ください。');}}
function stopSpeech(){speaking=null;if('speechSynthesis'in window)speechSynthesis.cancel();document.querySelectorAll('[data-speak]').forEach(b=>b.textContent='▶ 暗記法を読み上げ');}
function speak(id,button){if(speaking===id){stopSpeech();return;}stopSpeech();if(!('speechSynthesis'in window)){toast('このブラウザは読み上げに対応していません。');return;}const d=data.find(x=>x.id===id);if(!d?.speech){toast('H欄に読み上げ文がありません。');return;}const u=new SpeechSynthesisUtterance(d.speech);u.lang='ja-JP';u.rate=.88;speaking=id;button.textContent='■ 読み上げを止める';u.onend=()=>{if(speaking===id)stopSpeech();};u.onerror=()=>{if(speaking===id)stopSpeech();};speechSynthesis.speak(u);}
function beep(ok){if(!sound)return;try{audioCtx ||= new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();[...(ok?[660,880]:[240,180])].forEach((freq,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime+i*.14;o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.12,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+.18);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+.2);});}catch{}}
function page(html){stopSpeech();app.innerHTML=html;window.scrollTo(0,0);}
function soundLabel(){$('#sound').textContent=sound?'♪ 音 ON':'♪ 音 OFF';}
$('#sound').onclick=()=>{sound=!sound;soundLabel();try{localStorage.setItem('toki-sound',sound?'on':'off');}catch{}};
$('#home').onclick=()=>home();
const modeNames={input:'できごと → 年代',choice:'年代 → できごと',order:'近いできごとを並べ替え'};
function home(){page(`<section class="hero"><div class="eyebrow">A LITTLE HISTORY, EVERY DAY</div><h1>歴史の流れを、<br>ひとつずつ。</h1><p class="muted">年代とできごとを、あなたのペースで。</p></section><div class="stat"><span>覚えたできごと</span><b>${data.filter(d=>learned.has(d.id)).length} / ${data.length}</b></div><div class="modes">${Object.entries(modeNames).map(([k,v],i)=>`<button class="mode" data-mode="${k}"><span class="num">0${i+1}</span><span><b>${v}</b><small>${['大きな数字ボタンで入力','4つの選択肢から選ぶ','古い順にタップして並べる'][i]}</small></span></button>`).join('')}</div><div class="row" style="margin-top:22px"><button id="all-list">すべての問題</button><button id="learned-list">覚えた問題</button></div><details class="footer"><summary>使い方・データについて</summary><p>モードを選び、時代にチェックしてスタート。答え合わせの後は「次の問題」で進みます。覚えたチェックはいつでも外せます。記録はこのブラウザに保存されます。</p><p>時代・文章はCSV原文を使用。C欄が空白の${data.filter(d=>d.era==='時代未設定').length}件は「時代未設定」です。世紀表記の並べ替えは、その世紀の開始年を基準にします。同じ年代はCSV番号順、番号も同じならCSV行順です。</p></details>`);document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;settings();});$('#all-list').onclick=()=>list(false);$('#learned-list').onclick=()=>list(true);}
function settings(){const eras=[...new Set(data.map(d=>d.era))];if(!selected.size)selected=new Set(eras);page(`<div class="eyebrow">出題範囲</div><h1>${modeNames[mode]}</h1><p class="muted">出題する時代を、いくつでも選べます。</p><div class="row"><button id="select-all">すべて選ぶ</button><button id="select-none">すべて外す</button></div><div class="chips">${eras.map((e,i)=>`<label class="check"><input type="checkbox" data-era="${i}" ${selected.has(e)?'checked':''}><span>${esc(e)} <small>(${data.filter(d=>d.era===e).length})</small></span></label>`).join('')}</div><label class="check"><input id="exclude" type="checkbox" ${exclude?'checked':''}>覚えた問題を除く</label><p class="tip">C欄が空白の問題は「時代未設定」で選べます。${mode==='choice'?'正解・選択肢とも、選んだ範囲から出題します。異なる年代の選択肢が足りない問題は出題対象から外れます。':''}${mode==='order'?'近い年代の4件（少ない場合は2〜3件）を出題します。':''}</p><p id="count"></p><button id="start" class="primary wide">はじめる</button>`);
const update=()=>{pool=data.filter(d=>selected.has(d.era)&&(!exclude||!learned.has(d.id)));const eligible=eligiblePool();$('#count').textContent=`出題できる問題：${eligible.length}件${mode==='order'?' ／ 1回10問':''}`;$('#start').disabled=eligible.length<(mode==='order'?2:1);};document.querySelectorAll('[data-era]').forEach(b=>b.onchange=()=>{b.checked?selected.add(eras[b.dataset.era]):selected.delete(eras[b.dataset.era]);update();});$('#select-all').onclick=()=>{selected=new Set(eras);document.querySelectorAll('[data-era]').forEach(b=>b.checked=true);update();};$('#select-none').onclick=()=>{selected.clear();document.querySelectorAll('[data-era]').forEach(b=>b.checked=false);update();};$('#exclude').onchange=e=>{exclude=e.target.checked;update();};$('#start').onclick=()=>{queue=shuffle(eligiblePool());qIndex=0;correct=0;nextQuestion();};update();}
function distractors(d){return pool.filter(x=>x.year!==d.year&&x.event!==d.event).filter((x,i,a)=>a.findIndex(y=>y.event===x.event)===i);}
function eligiblePool(){return mode==='choice'?pool.filter(d=>distractors(d).length>=3):pool;}
function nextQuestion(){stopSpeech();if(qIndex>=(mode==='order'?10:queue.length)){finish();return;}answered=false;choice=null;order=[];digits='';current=queue[qIndex%queue.length];if(mode==='order'){const sorted=[...pool].sort(compare),anchor=sorted.indexOf(current),n=Math.min(4,sorted.length),start=Math.max(0,Math.min(sorted.length-n,anchor-Math.floor(Math.random()*n)));orderItems=shuffle(sorted.slice(start,start+n));if(orderItems.every((x,i)=>x===sorted[start+i]))orderItems.reverse();}renderQuestion();}
function renderQuestion(){const total=mode==='order'?10:queue.length;page(`<div class="row"><button id="back" class="quiet">← 範囲を変える</button><span class="muted" style="text-align:right">${qIndex+1} / ${total}問</span></div><div class="progress"><i style="width:${qIndex/total*100}%"></i></div><div class="eyebrow">${modeNames[mode]}</div><section class="card"><span class="tag">${mode==='order'?'古い → 新しい':esc(current.era)}</span><h2>${mode==='input'?esc(current.event):mode==='choice'?esc(displayYear(current.year))+'のできごとは？':'古い順にタップしよう'}</h2><div id="question-body"></div><button id="check" class="primary wide" disabled>答え合わせ</button><div id="feedback" aria-live="polite"></div></section>`);$('#back').onclick=settings;$('#check').onclick=check;
if(mode==='input'){const t=yearInfo(current.year);$('#question-body').innerHTML=`<div class="unit">${t.bc?'紀元前の年を入力':t.century?'何世紀？ 数字を入力':'西暦を入力'}</div><input id="year" aria-label="年代の数字" inputmode="numeric" pattern="[0-9]*" autocomplete="off" placeholder="？" maxlength="4"><div class="keys">${['1','2','3','4','5','6','7','8','9','消す','0','⌫'].map(k=>`<button data-key="${k}" type="button">${k}</button>`).join('')}</div>`;$('#year').oninput=e=>{digits=e.target.value.normalize('NFKC').replace(/\D/g,'').slice(0,4);e.target.value=digits;$('#check').disabled=!digits;};$('#year').onkeydown=e=>{if(e.key==='Enter'&&digits){e.preventDefault();check();}};document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{if(answered)return;digits=b.dataset.key==='消す'?'':b.dataset.key==='⌫'?digits.slice(0,-1):(digits+b.dataset.key).slice(0,4);$('#year').value=digits;$('#check').disabled=!digits;});}
if(mode==='choice'){const options=shuffle([current,...shuffle(distractors(current)).slice(0,3)]);$('#question-body').innerHTML=`<div class="choices">${options.map((d,i)=>`<button data-option="${esc(d.id)}">${i+1}. ${esc(d.event)}</button>`).join('')}</div>`;document.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>{if(answered)return;choice=b.dataset.option;document.querySelectorAll('[data-option]').forEach(x=>x.classList.toggle('selected',x===b));$('#check').disabled=false;});}
if(mode==='order')renderOrder();}
function renderOrder(){$('#question-body').innerHTML=`<p class="muted" style="font-size:13px">同じ年代は番号の小さい順。選んだものは「戻す」で選び直せます。</p><div>${Array.from({length:orderItems.length},(_,i)=>{const d=orderItems.find(x=>x.id===order[i]);return `<div class="order-slot">${i+1}. ${d?`<button data-undo="${i}">戻す</button><small>No.${esc(d.no)}</small> ${esc(d.event)}`:'未選択'}</div>`;}).join('')}</div><div class="choices">${orderItems.filter(d=>!order.includes(d.id)).map(d=>`<button data-order="${esc(d.id)}"><small>No.${esc(d.no)}</small> ${esc(d.event)}</button>`).join('')}</div>`;document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{if(answered)return;order.push(b.dataset.order);renderOrder();});document.querySelectorAll('[data-undo]').forEach(b=>b.onclick=()=>{if(answered)return;order.splice(Number(b.dataset.undo),1);renderOrder();});$('#check').disabled=order.length!==orderItems.length;}
function displayYear(y){return /^\d+$/.test(y)?y+'年':y.replace('B.C.','紀元前')+(/^B.C./.test(y)?'年':'');}
function answerCard(d,rank=''){return `<div class="answer-item"><b>${rank}${esc(displayYear(d.year))} <small>No.${esc(d.no)}</small></b><p>${esc(d.event)}</p><div class="memory">${esc(d.memory||'暗記法は未登録です。')}</div>${mode!=='order'?`<button data-speak="${esc(d.id)}" class="wide quiet">▶ 暗記法を読み上げ</button>`:''}<label class="check" style="margin-top:12px"><input type="checkbox" data-learn="${esc(d.id)}" ${learned.has(d.id)?'checked':''}>この問題を覚えた</label></div>`;}
function check(){if(answered)return;let ok;if(mode==='input'){if(!digits)return;ok=Number(digits)===yearInfo(current.year).n;}else if(mode==='choice'){if(choice===null)return;ok=choice===current.id;}else{if(order.length!==orderItems.length)return;ok=[...orderItems].sort(compare).every((x,i)=>x.id===order[i]);}answered=true;correct+=ok?1:0;beep(ok);$('#check').hidden=true;document.querySelectorAll('#question-body button,#question-body input').forEach(b=>b.disabled=true);if(mode==='choice')document.querySelectorAll('[data-option]').forEach(b=>{if(b.dataset.option===current.id)b.classList.add('good');else if(b.dataset.option===choice)b.classList.add('bad');});const answers=mode==='order'?[...orderItems].sort(compare):[current];$('#feedback').innerHTML=`<div class="result ${ok?'':'wrong'}"><h2>${ok?'○ 正解！':'× おしい！'}</h2><span>${ok?'この調子で覚えていこう。':'正しい答えを確認しよう。'}</span>${mode==='input'&&!ok?`<p>あなたの回答：${esc(digits)}${yearInfo(current.year).century?'世紀':'年'}</p>`:''}${mode==='order'?'<p>正しい順番 ↓</p>':''}${answers.map((d,i)=>answerCard(d,mode==='order'?`${i+1}. `:'')).join('')}</div><button id="next" class="primary wide">次の問題 →</button>`;bindAnswer();$('#next').onclick=()=>{qIndex++;nextQuestion();};$('#feedback').scrollIntoView({behavior:'auto',block:'nearest'});}
function bindAnswer(){document.querySelectorAll('[data-learn]').forEach(b=>b.onchange=()=>setLearned(b.dataset.learn,b.checked));document.querySelectorAll('[data-speak]').forEach(b=>b.onclick=()=>speak(b.dataset.speak,b));}
function finish(){page(`<section class="card"><div class="eyebrow">おつかれさまでした</div><h1>今日の一歩、完了。</h1><p>正解 <b>${correct}</b> / ${qIndex}問</p><button id="again" class="primary wide">範囲を選んでもう一度</button><button id="go-home" class="wide">ホームへ</button></section>`);$('#again').onclick=settings;$('#go-home').onclick=home;}
function list(onlyLearned){page(`<div class="eyebrow">歴史の一覧</div><h1>できごと手帳</h1><input id="search" type="search" placeholder="年号・できごと・暗記法で検索" aria-label="問題を検索"><div class="row" style="margin-top:12px"><select id="list-era" aria-label="時代で絞り込む"><option value="">すべての時代</option>${[...new Set(data.map(d=>d.era))].map(e=>`<option>${esc(e)}</option>`).join('')}</select><select id="list-status" aria-label="記憶状態で絞り込む"><option value="all">すべて</option><option value="yes" ${onlyLearned?'selected':''}>覚えた問題</option><option value="no">まだ覚えていない</option></select></div><p id="list-count" class="muted"></p><p class="muted" style="font-size:12px">表は横にスクロールできます。チェックは外すこともできます。</p><div id="list-results"></div>`);function update(){stopSpeech();const query=$('#search').value.normalize('NFKC').toLowerCase().trim(),era=$('#list-era').value,status=$('#list-status').value,rows=data.filter(d=>(!era||d.era===era)&&(status==='all'||learned.has(d.id)===(status==='yes'))&&[d.no,d.year,d.era,d.event,d.memory].join(' ').normalize('NFKC').toLowerCase().includes(query));$('#list-count').textContent=`${rows.length}件 / 全${data.length}件`;$('#list-results').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>覚えた</th><th>番号</th><th>年代 / 時代</th><th>できごと</th><th>暗記法</th></tr></thead><tbody>${rows.map(d=>`<tr><td><input type="checkbox" aria-label="${esc(d.event)}を覚えた" data-list-learn="${esc(d.id)}" ${learned.has(d.id)?'checked':''}></td><td>${esc(d.no)}</td><td>${esc(displayYear(d.year))}<br><small>${esc(d.era)}</small></td><td>${esc(d.event)}</td><td>${esc(d.memory)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="card">該当する問題はありません。</p>';document.querySelectorAll('[data-list-learn]').forEach(b=>b.onchange=()=>{setLearned(b.dataset.listLearn,b.checked);update();});}$('#search').oninput=update;$('#list-era').onchange=update;$('#list-status').onchange=update;update();}
async function init(){let text=window.HISTORY_CSV;try{if(location.protocol!=='file:'){const r=await fetch('history.csv',{cache:'no-store'});if(!r.ok)throw Error();text=await r.text();}}catch{toast('同梱の問題データを読み込みました。');}data=parseCSV(text).slice(1).filter(r=>r[1]?.trim()&&r[5]?.trim()).map((r,i)=>({id:JSON.stringify([r[0],r[1],r[5]]),row:i,no:r[0],year:r[1].trim(),era:r[2].trim()||'時代未設定',event:r[5],memory:r[6]||'',speech:r[7]||''}));if(!data.length){page('<p>問題データがありません。history.csvを確認してください。</p>');return;}soundLabel();home();}
window.addEventListener('pagehide',stopSpeech);init();
